[2025-07-04T05:33:26.908+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-04T05:33:26.942+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: products_prices_dag.mail_group.generate_email scheduled__2025-07-03T00:00:00+00:00 [queued]>
[2025-07-04T05:33:26.952+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: products_prices_dag.mail_group.generate_email scheduled__2025-07-03T00:00:00+00:00 [queued]>
[2025-07-04T05:33:26.953+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2025-07-04T05:33:26.970+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): mail_group.generate_email> on 2025-07-03 00:00:00+00:00
[2025-07-04T05:33:26.979+0000] {standard_task_runner.py:63} INFO - Started process 4720 to run task
[2025-07-04T05:33:26.985+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'products_prices_dag', 'mail_group.generate_email', 'scheduled__2025-07-03T00:00:00+00:00', '--job-id', '216', '--raw', '--subdir', 'DAGS_FOLDER/products_prices_dag.py', '--cfg-path', '/tmp/tmpwp3yybps']
[2025-07-04T05:33:26.990+0000] {standard_task_runner.py:91} INFO - Job 216: Subtask mail_group.generate_email
[2025-07-04T05:33:27.020+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-04T05:33:27.104+0000] {task_command.py:426} INFO - Running <TaskInstance: products_prices_dag.mail_group.generate_email scheduled__2025-07-03T00:00:00+00:00 [running]> on host e43ce2a1e7a4
[2025-07-04T05:33:27.274+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='karthik' AIRFLOW_CTX_DAG_ID='products_prices_dag' AIRFLOW_CTX_TASK_ID='mail_group.generate_email' AIRFLOW_CTX_EXECUTION_DATE='2025-07-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-03T00:00:00+00:00'
[2025-07-04T05:33:27.283+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-04T05:33:27.414+0000] {python.py:237} INFO - Done. Returned value was: <p>Price drop report attached.</p>
[2025-07-04T05:33:27.416+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-04T05:33:27.464+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=products_prices_dag, task_id=mail_group.generate_email, run_id=scheduled__2025-07-03T00:00:00+00:00, execution_date=20250703T000000, start_date=20250704T053326, end_date=20250704T053327
[2025-07-04T05:33:27.479+0000] {taskinstance.py:1182} ERROR - Error when executing success_slack_msg callback
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1179, in _run_finished_callback
    callback(context)
  File "/opt/airflow/dags/products_prices_dag.py", line 35, in success_slack_msg
    webhook_token=Variable.get("slack_webhook"),
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable slack_webhook does not exist'
[2025-07-04T05:33:27.563+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-07-04T05:33:27.609+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-07-04T05:33:27.614+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
