[2025-07-04T05:33:13.046+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-04T05:33:13.077+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: products_prices_dag.create_table scheduled__2025-07-03T00:00:00+00:00 [queued]>
[2025-07-04T05:33:13.087+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: products_prices_dag.create_table scheduled__2025-07-03T00:00:00+00:00 [queued]>
[2025-07-04T05:33:13.088+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2025-07-04T05:33:13.126+0000] {taskinstance.py:2330} INFO - Executing <Task(MySqlOperator): create_table> on 2025-07-03 00:00:00+00:00
[2025-07-04T05:33:13.138+0000] {standard_task_runner.py:63} INFO - Started process 4705 to run task
[2025-07-04T05:33:13.145+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'products_prices_dag', 'create_table', 'scheduled__2025-07-03T00:00:00+00:00', '--job-id', '211', '--raw', '--subdir', 'DAGS_FOLDER/products_prices_dag.py', '--cfg-path', '/tmp/tmp9j_b2h0z']
[2025-07-04T05:33:13.150+0000] {standard_task_runner.py:91} INFO - Job 211: Subtask create_table
[2025-07-04T05:33:13.176+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-04T05:33:13.240+0000] {task_command.py:426} INFO - Running <TaskInstance: products_prices_dag.create_table scheduled__2025-07-03T00:00:00+00:00 [running]> on host e43ce2a1e7a4
[2025-07-04T05:33:13.342+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='karthik' AIRFLOW_CTX_DAG_ID='products_prices_dag' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2025-07-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-03T00:00:00+00:00'
[2025-07-04T05:33:13.345+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-04T05:33:13.360+0000] {sql.py:276} INFO - Executing: 
        CREATE TABLE IF NOT EXISTS products_table (
            product_id INT NOT NULL,
            product_name VARCHAR(200),
            price DECIMAL(10,2),
            category VARCHAR(100),
            description TEXT,
            image_link VARCHAR(200),
            rating DECIMAL(10,2),
            rating_count INT,
            date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            PRIMARY KEY(product_id, date)
        );
        
[2025-07-04T05:33:13.372+0000] {base.py:84} INFO - Using connection ID 'mysql_conn' for task execution.
[2025-07-04T05:33:13.383+0000] {base.py:84} INFO - Using connection ID 'mysql_conn' for task execution.
[2025-07-04T05:33:13.410+0000] {sql.py:487} INFO - Running statement: 
        CREATE TABLE IF NOT EXISTS products_table (
            product_id INT NOT NULL,
            product_name VARCHAR(200),
            price DECIMAL(10,2),
            category VARCHAR(100),
            description TEXT,
            image_link VARCHAR(200),
            rating DECIMAL(10,2),
            rating_count INT,
            date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            PRIMARY KEY(product_id, date)
        );
        , parameters: None
[2025-07-04T05:33:13.416+0000] {sql.py:496} INFO - Rows affected: 0
[2025-07-04T05:33:13.418+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-04T05:33:13.430+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=products_prices_dag, task_id=create_table, run_id=scheduled__2025-07-03T00:00:00+00:00, execution_date=20250703T000000, start_date=20250704T053313, end_date=20250704T053313
[2025-07-04T05:33:13.436+0000] {taskinstance.py:1182} ERROR - Error when executing success_slack_msg callback
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1179, in _run_finished_callback
    callback(context)
  File "/opt/airflow/dags/products_prices_dag.py", line 35, in success_slack_msg
    webhook_token=Variable.get("slack_webhook"),
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable slack_webhook does not exist'
[2025-07-04T05:33:13.480+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-07-04T05:33:13.495+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/models/baseoperator.py:1297 AirflowProviderDeprecationWarning: Call to deprecated class MySqlOperator. (Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
[2025-07-04T05:33:13.514+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-07-04T05:33:13.517+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
