[2025-07-04T05:41:26.082+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-04T05:41:26.136+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: products_prices_dag.end_dag scheduled__2025-07-03T00:00:00+00:00 [queued]>
[2025-07-04T05:41:26.152+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: products_prices_dag.end_dag scheduled__2025-07-03T00:00:00+00:00 [queued]>
[2025-07-04T05:41:26.154+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 4
[2025-07-04T05:41:26.185+0000] {taskinstance.py:2330} INFO - Executing <Task(EmptyOperator): end_dag> on 2025-07-03 00:00:00+00:00
[2025-07-04T05:41:26.197+0000] {standard_task_runner.py:63} INFO - Started process 5021 to run task
[2025-07-04T05:41:26.206+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'products_prices_dag', 'end_dag', 'scheduled__2025-07-03T00:00:00+00:00', '--job-id', '224', '--raw', '--subdir', 'DAGS_FOLDER/products_prices_dag.py', '--cfg-path', '/tmp/tmpc74e9zx0']
[2025-07-04T05:41:26.214+0000] {standard_task_runner.py:91} INFO - Job 224: Subtask end_dag
[2025-07-04T05:41:26.256+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-04T05:41:26.357+0000] {task_command.py:426} INFO - Running <TaskInstance: products_prices_dag.end_dag scheduled__2025-07-03T00:00:00+00:00 [running]> on host e43ce2a1e7a4
[2025-07-04T05:41:26.553+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='karthik' AIRFLOW_CTX_DAG_ID='products_prices_dag' AIRFLOW_CTX_TASK_ID='end_dag' AIRFLOW_CTX_EXECUTION_DATE='2025-07-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-03T00:00:00+00:00'
[2025-07-04T05:41:26.556+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-04T05:41:26.583+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-04T05:41:26.604+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=products_prices_dag, task_id=end_dag, run_id=scheduled__2025-07-03T00:00:00+00:00, execution_date=20250703T000000, start_date=20250704T054126, end_date=20250704T054126
[2025-07-04T05:41:26.658+0000] {taskinstance.py:1182} ERROR - Error when executing success_slack_msg callback
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1179, in _run_finished_callback
    callback(context)
  File "/opt/airflow/dags/products_prices_dag.py", line 36, in success_slack_msg
    webhook_token=Variable.get("slack_webhook"),
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable slack_webhook does not exist'
[2025-07-04T05:41:26.743+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-07-04T05:41:26.777+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-04T05:41:26.808+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
