[2025-07-04T05:36:13.851+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-04T05:36:13.908+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: products_prices_dag.end_dag scheduled__2025-07-03T00:00:00+00:00 [queued]>
[2025-07-04T05:36:13.923+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: products_prices_dag.end_dag scheduled__2025-07-03T00:00:00+00:00 [queued]>
[2025-07-04T05:36:13.924+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2025-07-04T05:36:13.977+0000] {taskinstance.py:2330} INFO - Executing <Task(EmptyOperator): end_dag> on 2025-07-03 00:00:00+00:00
[2025-07-04T05:36:13.983+0000] {standard_task_runner.py:63} INFO - Started process 4839 to run task
[2025-07-04T05:36:13.987+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'products_prices_dag', 'end_dag', 'scheduled__2025-07-03T00:00:00+00:00', '--job-id', '220', '--raw', '--subdir', 'DAGS_FOLDER/products_prices_dag.py', '--cfg-path', '/tmp/tmpm812o7v0']
[2025-07-04T05:36:13.992+0000] {standard_task_runner.py:91} INFO - Job 220: Subtask end_dag
[2025-07-04T05:36:14.026+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-04T05:36:14.127+0000] {task_command.py:426} INFO - Running <TaskInstance: products_prices_dag.end_dag scheduled__2025-07-03T00:00:00+00:00 [running]> on host e43ce2a1e7a4
[2025-07-04T05:36:14.328+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='karthik' AIRFLOW_CTX_DAG_ID='products_prices_dag' AIRFLOW_CTX_TASK_ID='end_dag' AIRFLOW_CTX_EXECUTION_DATE='2025-07-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-03T00:00:00+00:00'
[2025-07-04T05:36:14.331+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-04T05:36:14.359+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-04T05:36:14.379+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=products_prices_dag, task_id=end_dag, run_id=scheduled__2025-07-03T00:00:00+00:00, execution_date=20250703T000000, start_date=20250704T053613, end_date=20250704T053614
[2025-07-04T05:36:14.414+0000] {taskinstance.py:1182} ERROR - Error when executing success_slack_msg callback
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1179, in _run_finished_callback
    callback(context)
  File "/opt/airflow/dags/products_prices_dag.py", line 35, in success_slack_msg
    webhook_token=Variable.get("slack_webhook"),
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable slack_webhook does not exist'
[2025-07-04T05:36:14.485+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-07-04T05:36:14.519+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-04T05:36:14.525+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
