[2025-07-04T03:59:54.443+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-04T03:59:54.677+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: products_prices_dag.ETL_group.load_products scheduled__2025-07-03T00:00:00+00:00 [queued]>
[2025-07-04T03:59:54.693+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: products_prices_dag.ETL_group.load_products scheduled__2025-07-03T00:00:00+00:00 [queued]>
[2025-07-04T03:59:54.695+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 4
[2025-07-04T03:59:54.750+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): ETL_group.load_products> on 2025-07-03 00:00:00+00:00
[2025-07-04T03:59:54.765+0000] {standard_task_runner.py:63} INFO - Started process 1653 to run task
[2025-07-04T03:59:54.773+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'products_prices_dag', 'ETL_group.load_products', 'scheduled__2025-07-03T00:00:00+00:00', '--job-id', '176', '--raw', '--subdir', 'DAGS_FOLDER/products_prices_dag.py', '--cfg-path', '/tmp/tmpmpeghew8']
[2025-07-04T03:59:54.779+0000] {standard_task_runner.py:91} INFO - Job 176: Subtask ETL_group.load_products
[2025-07-04T03:59:54.812+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-04T03:59:54.882+0000] {task_command.py:426} INFO - Running <TaskInstance: products_prices_dag.ETL_group.load_products scheduled__2025-07-03T00:00:00+00:00 [running]> on host e43ce2a1e7a4
[2025-07-04T03:59:55.042+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='karthik' AIRFLOW_CTX_DAG_ID='products_prices_dag' AIRFLOW_CTX_TASK_ID='ETL_group.load_products' AIRFLOW_CTX_EXECUTION_DATE='2025-07-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-03T00:00:00+00:00'
[2025-07-04T03:59:55.044+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-04T03:59:05.983+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-04T03:59:05.984+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/scripts/fakestoreapi/get_products.py", line 72, in load_data
    price = float(row['price'], 2)
TypeError: float expected at most 1 argument, got 2
[2025-07-04T03:59:06.021+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=products_prices_dag, task_id=ETL_group.load_products, run_id=scheduled__2025-07-03T00:00:00+00:00, execution_date=20250703T000000, start_date=20250704T035954, end_date=20250704T035906
[2025-07-04T03:59:06.046+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 176 for task ETL_group.load_products (float expected at most 1 argument, got 2; 1653)
[2025-07-04T03:59:06.085+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-07-04T03:59:06.124+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-04T03:59:06.132+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
